### ISSUE TITLE
Unable to Extract listview Text from the Application

### ISSUE THREAD

**Issue by indudhargowda** [2gis/Winium#3]
![list](https://cloud.githubusercontent.com/assets/10906289/9938522/5dbcc148-5d83-11e5-9443-d3c944088ddd.png)

Unable to Extract listview Text from the Application and unable to window in UI Spy but able to get window inspect.

Requirement extract names which contains "High Priority" in VB.net Loop till its Blank.
Tried the Below code not working

window = driver.FindElementByClassName("SWT_Window0")
Dim els As IList(Of IWebElement) = window.FindElements(By.Name("High"))
' Dim els As IList(Of IWebElement) = window.FindElements(By.XPath("//*[contains(@Name, 'High Priority')]"))
Debug.Print(els(0).GetAttribute("name"))
Debug.Print(els(0).GetAttribute("AutomationId"))
Debug.Print(els(0).GetAttribute("ControlType"))

==================Inspect element Code==================
How found: Focus
Name: "High Priority DP Service Desk DP Shared Hub Notification - Application Upgrade November 1st 2015 09/17/2015 01:02 PM 62K"
ControlType: UIA_ListItemControlTypeId (0xC357)
LocalizedControlType: "list item"
BoundingRectangle: {l:928 t:192 r:1328 b:236}
IsEnabled: true
IsOffscreen: false
IsKeyboardFocusable: true
HasKeyboardFocus: true
AccessKey: ""
ProcessId: 3316
RuntimeId: [2A.20708.2.80000001.20708.FFFFFFFC.2]
ProviderDescription: "[pid:3316,hwnd:0x0 Annotation:Microsoft: Annotation Proxy (unmanaged:uiautomationcore.dll); Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]"
IsPeripheral: [Not supported]
LiveSettingProperty: [Not supported]
IsPassword: false
HelpText: ""
FlowsFrom: [Not supported]
OptimizeForVisualContent: [Not supported]
PositionInSet: [Not supported]
SizeOfSet: [Not supported]
Level: [Not supported]
AnnotationTypes: [Not supported]
AnnotationObjects: [Not supported]
Annotation.AnnotationAuthor: [Not supported]
Annotation.AnnotationTypeId: [Not supported]
Annotation.Author: [Not supported]
Annotation.DateTime: [Not supported]
Annotation.Target: [Not supported]
Drag.DropEffect: [Not supported]
Drag.DropEffects: [Not supported]
Drag.GrabbedItems: [Not supported]
Drag.IsGrabbed: [Not supported]
DropTarget.DropTargetEffect: [Not supported]
DropTarget.DropTargetEffects: [Not supported]
LegacyIAccessible.ChildId: 2
LegacyIAccessible.DefaultAction: "Press"
LegacyIAccessible.Description: ""
LegacyIAccessible.Help: ""
LegacyIAccessible.KeyboardShortcut: ""
LegacyIAccessible.Name: "High Priority DP Service Desk DP Shared Hub Notification - Application Upgrade November 1st 2015 09/17/2015 01:02 PM 62K"
LegacyIAccessible.Role: list item (0x22)
LegacyIAccessible.State: selected,focused,focusable,selectable,multiple selectable (0x1300006)
LegacyIAccessible.Value: "1 Unread"
ObjectModel.UnderlyingObjectModel: [Error: calling getter for this property: hr=0x80070057 - The parameter is incorrect.]
SelectionItem.IsSelected: true
SelectionItem.SelectionContainer: "Inbox" list
SpreadsheetItem.AnnotationObjects: [Not supported]
SpreadsheetItem.AnnotationTypes: [Not supported]
SpreadsheetItem.Formula: [Not supported]
Style.ExtendedProperties: [Not supported]
Style.FillColor: [Not supported]
Style.FillPatternColor: [Not supported]
Style.FillPatternStyle: [Not supported]
Style.Shape: [Not supported]
Style.StyleId: [Not supported]
Style.StyleName: [Not supported]
Value.IsReadOnly: false
Value.Value: "1 Unread"
Transform2.CanZoom: [Not supported]
Transform2.ZoomLevel: [Not supported]
Transform2.ZoomMinimum: [Not supported]
Transform2.ZoomMaximum: [Not supported]
IsAnnotationPatternAvailable: [Not supported]
IsDragPatternAvailable: [Not supported]
IsDockPatternAvailable: false
IsDropTargetPatternAvailable: [Not supported]
IsExpandCollapsePatternAvailable: false
IsGridItemPatternAvailable: false
IsGridPatternAvailable: false
IsInvokePatternAvailable: true
IsItemContainerPatternAvailable: false
IsLegacyIAccessiblePatternAvailable: true
IsMultipleViewPatternAvailable: false
IsObjectModelPatternAvailable: [Not supported]
IsRangeValuePatternAvailable: false
IsScrollItemPatternAvailable: false
IsScrollPatternAvailable: false
IsSelectionItemPatternAvailable: true
IsSelectionPatternAvailable: false
IsSpreadsheetItemPatternAvailable: [Not supported]
IsSpreadsheetPatternAvailable: [Not supported]
IsStylesPatternAvailable: [Not supported]
IsSynchronizedInputPatternAvailable: false
IsTableItemPatternAvailable: false
IsTablePatternAvailable: false
IsTextChildPatternAvailable: [Not supported]
IsTextEditPatternAvailable: [Not supported]
IsTextPatternAvailable: false
IsTextPattern2Available: [Not supported]
IsTogglePatternAvailable: false
IsTransformPatternAvailable: false
IsTransform2PatternAvailable: [Not supported]
IsValuePatternAvailable: true
IsVirtualizedItemPatternAvailable: false
IsWindowPatternAvailable: false
IsCustomNavigationPatternAvailable: [Not supported]
FirstChild: [null]
LastChild: [null]
Next: "High Priority Aola Collapsed Twistie Icon Dump (2 thread documents) 09/16/2015 06:03 PM 2K" list item
Previous: "Expanded Twistie Icon High Importance" list item
Other Props: Object has no additional properties
Children: Container has no children
Ancestors: "Inbox" list
"" pane
"" pane
"" pane
"" pane
"" pane
"" pane
"" pane
"" pane
"" pane
"" pane
"" pane
"Mail - Inbox - Notes" window
"Desktop" pane
[ No Parent ]

**Comment by NickAb** [comment]
I am not sure, but it seems that you are trying to locate elements using partial name
```vb
Dim els As IList(Of IWebElement) = window.FindElements(By.Name("High"))
```

When trying to find elements using `Name` strategy a full name should be specified. 
You can try finding root element `Inbox` by name and the finding all child elements of `Inbox` by their class name (something like `ListItem`). After that you can iterate found elements and check their `name` attribute to filter high priority ones.

**Comment by indudhargowda** [comment]
Can you please give me an example , so that it will be helpful for me.

Root : Inbox, .....extract Child elements name by for loop.

**Comment by NickAb** [comment]
It is hard to give correct example without proper knowledge of UI structure. Also I don't know Visual Basic, so here is a sample that might need syntax fixing:
```vb
Dim inbox As IWebElement = window.FindElement(By.Name("Inbox"))
Dim els As IList(Of IWebElement) = inbox.FindElements(By.ClassName("UIA_ListItemControlTypeId")) // replace UIA_ListItemControlTypeId with actual class name of list item
Dim highPriority = From item In els Where item.GetAttribute("Name").StartsWith("High")
```

Here is the same thing in python for reference:
```py
inbox = window.find_element_by_name("Inbox")
items = inbox.find_elements_by_class_name("UIA_ListItemControlTypeId") #replace UIA_ListItemControlTypeId with actual class name of list item
high_priority = [x for x in items if x..get_attribute("Name").startswith("High")]
```

**Comment by indudhargowda** [comment]
Still its Not working.Kindly find the Screen Shot.
![check2](https://cloud.githubusercontent.com/assets/10906289/9955149/6c1e20ea-5e0c-11e5-9332-2846ad5b9638.png)
![check](https://cloud.githubusercontent.com/assets/10906289/9955150/6c248c3c-5e0c-11e5-86aa-02dcd160e489.png)

If i find the Ui element in UI Spy its not showing ....but if i use VisualUIAVerify.exe...The elements Name is Showing....

**Comment by tkurnosova** [comment]
FindElementByClassName(string) it is not the same as FindElementByClassName("ControlType.<ControlType>"). Now there is no way to get control by its ControlType. 
In your example ClassName and AutomationId of list box item are empty. You can get control by full name using FindElementByClassName or get all available elements within list "Inbox"

**Comment by indudhargowda** [comment]
Can u guide me to get all available elements within list "Inbox"..
If you provide me an example will try Now..

**Comment by tkurnosova** [comment]
You can try 
Dim inbox As IWebElement = window.FindElement(By.Name("Inbox"))
Dim els As IList(Of IWebElement) = inbox.FindElements(By.ClassName(""))

**Comment by indudhargowda** [comment]
Almost there....But I did not get the desired out.
![checkpng](https://cloud.githubusercontent.com/assets/10906289/9957914/048bab1c-5e22-11e5-8dd6-3de53b120168.png)

**Comment by skyline-gleb** [comment]
your driver running as administrator?

**Comment by indudhargowda** [comment]
yes

**Comment by indudhargowda** [comment]
![check](https://cloud.githubusercontent.com/assets/10906289/9958073/8e5ee01a-5e23-11e5-8afd-f2aae6687f31.png)
![check1](https://cloud.githubusercontent.com/assets/10906289/9958077/91f9eb7a-5e23-11e5-9135-d550db1132b4.png)
![check3](https://cloud.githubusercontent.com/assets/10906289/9958078/9a4ed060-5e23-11e5-9577-8de0d92c9419.png)

**Comment by indudhargowda** [comment]
Just need list items Names in Inbox...... Just Now found there are 2 element Name Inbox

**Comment by indudhargowda** [comment]
Can some 1 Help me in this....I am not getting the output..

**Comment by NickAb** [comment]
Is the application your are trying to automate is some standard or freely available windows application, so that we can try scripts out?

You can try searching for `Inbox` using AutomationId to make sure that you found correct element:
```
Dim inbox As IWebElement = window.FindElement(By.Id("1182472"))
Dim els As IList(Of IWebElement) = inbox.FindElements(By.ClassName(""))
```
Does it work, is `els` empty or does it contain as much elements, as your list does + scrollbox?

**Comment by indudhargowda** [comment]
No its not working, Id is variable,
![check](https://cloud.githubusercontent.com/assets/10906289/9963643/e63f353e-5e49-11e5-92f6-595b9dd30fe2.png)

**Comment by indudhargowda** [comment]
If i find the Ui element in UI Spy app its not showing elements ....but if i use VisualUIAVerify.exe...The elements Name is Showing....

**Comment by indudhargowda** [comment]
See the Code for Coded UI to find by Name : This might help,

![untitled](https://cloud.githubusercontent.com/assets/10906289/9974233/655bc90a-5ea3-11e5-956d-499b6c7f0bc7.png)

**Comment by indudhargowda** [comment]
Tried below code to find at least 1 Name still its not Working
![untitled](https://cloud.githubusercontent.com/assets/10906289/9974306/9075b788-5ea6-11e5-9c29-ef7c81f7e827.png)

**Comment by indudhargowda** [comment]
Ui Spy Output Once i click on 1 list item

Exception
Time Stamp : 9/19/2015 8:35 AM
Element : Element details not available.
Name : TreeValidationException
Message : UI Automation tree navigation is broken. The parent of one of the descendants exist but the descendant is not the child of the parent
Stack Trace :    at UISpy.Base.Tree.BuildTree(AutomationElement element)
   at UISpy.Base.Tree.BuildTreeAndRelatedTrees(AutomationElement element)

Focus Change Event
Time Stamp : 9/19/2015 8:35:15 AM
Element : "list item" "High Priority Amla Collapsed ..."
Object ID : -4
Child ID : 2

**Comment by NickAb** [comment]
Can you try searching for one of the items by name not from `Inbox` but  from `window`?

```vb
Dim els As IList(Of IWebElement) = window.FindElements(By.Name("Hight Priority ...")) ' put correct full name instead of partial
```

**Comment by indudhargowda** [comment]
I had done the same but unable to find the element

Dim els As IList(Of IWebElement) = window.FindElements(By.Name("Hight Priority amol was busy in the work shop"))
