### ISSUE TITLE
Winium crash on windows 10 and Java

### ISSUE THREAD

**Issue by SergeyPirogov** [2gis/Winium#34]
I am trying to run simple example with calc.exe using Java 8

I've added dependency and did everything as in example, but getting error

```
Starting Windows Desktop Driver on port 9999

18:21:14 [DEBUG] Waiting for a connection...

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'nb-sepi', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: WiniumDriver

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.winium.WiniumDriver.<init>(WiniumDriver.java:75)
	at com.example.CalculatorTest.calc_test(CalculatorTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:76)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:171)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:185)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:177)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:166)
	at org.openqa.selenium.winium.WiniumDriverCommandExecutor.execute(WiniumDriverCommandExecutor.java:72)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:620)

```

**Comment by NickAb** [comment]
Could you please provide code used to init webDriver in your tests?
`org.openqa.selenium.remote.UnreachableBrowserException` suggests that it is likely that there is some misconfiguration, e.g. you start driver without `wd/hub` url prefix, but selenium bindings expect driver to use this prefix, or there is misconfiguration of port.

@skyline-gleb

**Comment by SergeyPirogov** [comment]
Yes, I deleted lines and error gone 
```
.withVerbose(true)
.withSilent(false);
```

**Comment by SergeyPirogov** [comment]
@NickAb Is it possible to interact with remote winium driver using WiniumDriver class or I should use only bare Selenium RemoteDriver?

**Comment by NickAb** [comment]
@SergeyPirogov it should be possible, both [C#](https://github.com/2gis/Winium/blob/master/dotnet/src/OpenQA.Selenium.Winium/WiniumDriver.cs#L109) and [Java](https://github.com/2gis/Winium/blob/master/java/src/main/java/org/openqa/selenium/winium/WiniumDriver.java#L83) implementations have a constructor that takes remote address as a parameter.

But I have not used it that way myself (as I use Winium.Mobile from python code using Appium bindings). Maybe @skyline-gleb could give more details on that.

**Comment by NickAb** [comment]
@SergeyPirogov did it work for you?

**Comment by anileapencylon** [comment]
Hi,
I am running few test using Winium . For some reason after running the test my application (.exe) that I am using crashes. So I can't continue the test. Could someone provide some ideas please.
Thanks

**Comment by anileapencylon** [comment]
Forgot to mention I am also using Extent Reports in Visual studio.
I am using the below:
[OneTimeSetUp]
public void BeforeClass()
{
try
{
//To create report directory and add HTML report into it

            extent = new ExtentReports();
            var dir = AppDomain.CurrentDomain.BaseDirectory.Replace("\\bin\\Debug", "");
            DirectoryInfo di = Directory.CreateDirectory(dir + "\\Test_Execution_Reports");
            var htmlReporter = new ExtentHtmlReporter(dir + "\\Test_Execution_Reports" + "\\Automation_Report" + ".html");
            extent.AddSystemInfo("Application", "CXPro 1.01B351");
            extent.AddSystemInfo("User Name", "Product Development");
            extent.AttachReporter(htmlReporter);
        }
        catch (Exception e)
        {
            throw (e);
        }

        try
        {
            var service = WiniumDriverService.CreateDesktopService(@"C:\Users\anil.Pallithekethil\Downloads\Winium.Desktop.Driver");
            var options = new DesktopOptions { ApplicationPath = @"C:\CXpro101324\Port32Ex.exe" };
            driver = new WiniumDriver(service, options);

            Thread.Sleep(5000);

           // driver.FindElementByName("OK").Click();
        }
        catch (Exception e)
        {
            throw (e);
        }
    }
